import tkinter as tk
import networkx as nx


class NetworkGUI:
    def __init__(self, graph):
        self.canvas_width = 800
        self.canvas_height = 500
        self.graph = graph
        top = tk.Tk()
        top.title("test gui")
        self.canvas = tk.Canvas(top, width=800, height=500, bg='white')
        self.draw_graph()
        self.canvas.pack()
        top.mainloop()

    def draw_graph(self):
        '''
        TODO:
            currently, the graph area is hardcoded to be square and 50 pixels smaller than the canvas to make sure all nodes
            are drawn completely, fix ugly hardcoded positioning and maybe make dynamic?
        '''
        layout = nx.spring_layout(self.graph, scale=min(self.canvas_width-50, self.canvas_height-50)/2)
        # networkx places nodes in a box centered at zero, if scale is specified as x, then nodes will be in
        # [-x, x]
        # for now, place all nodes in a square with size dependent on the smaller of the canvas dimensions
        width = min(self.canvas_width-50, self.canvas_height-50)/2

        #  Nodes

        for node in layout.keys():
            pos = layout[node]
            # shift positions to right upper quadrant instead of centered around 0
            x,y = pos[0], pos[1]
            x,y = self._translate_pos(x,y)
            self.place_node(x,y)

        #  Connections

        for edge in self.graph.edges():
            n1, n2 = edge
            n1pos = layout[n1]
            n2pos = layout[n2]
            x1,y1 = self._translate_pos(n1pos[0], n1pos[1])
            x2,y2 = self._translate_pos(n2pos[0], n2pos[1])
            self.draw_connection((x1,y1), (x2,y2))



    def place_node(self, xpos, ypos, diam=20):
        x1 = xpos - diam/2
        y1 = ypos - diam/2
        x2 = xpos + diam/2
        y2 = ypos + diam/2

        self.canvas.create_oval(x1,y1,x2,y2,outline="black", fill="black")


    def draw_connection(self, n1pos, n2pos):
        self.canvas.create_line(n1pos[0], n1pos[1], n2pos[0], n2pos[1])


    def _translate_pos(self, x,y, padding=50):
        '''
        translate position generated by networkx to canvas position
        '''
        width = min(self.canvas_width-padding, self.canvas_height-padding)/2
        x_canv = x/2 + width/2 + padding/2
        y_canv = y/2 + width/2 + padding/2
        return x_canv, y_canv



if __name__ == "__main__":
    G = nx.Graph()
    G.add_node(1)
    G.add_node(2)
    G.add_node(3)
    G.add_edge(1,2)
    G.add_edge(2,3)
    G.add_edge(3,1)

    gui = NetworkGUI(G)
